[package]
name = "aoc2022-rust"
version = "0.1.0"
authors = ["Marcin Puc <tranzystorek.io@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "d01p1"
path = "src/days/d01p1.rs"

[[bin]]
name = "d01p2"
path = "src/days/d01p2.rs"

[[bin]]
name = "d02p1"
path = "src/days/d02p1.rs"

[[bin]]
name = "d02p2"
path = "src/days/d02p2.rs"

[[bin]]
name = "d03p1"
path = "src/days/d03p1.rs"

[[bin]]
name = "d03p2"
path = "src/days/d03p2.rs"

[[bin]]
name = "d04p1"
path = "src/days/d04p1.rs"

[[bin]]
name = "d04p2"
path = "src/days/d04p2.rs"

[[bin]]
name = "d05p1"
path = "src/days/d05p1.rs"

[[bin]]
name = "d05p2"
path = "src/days/d05p2.rs"

[[bin]]
name = "d06p1"
path = "src/days/d06p1.rs"

[[bin]]
name = "d06p2"
path = "src/days/d06p2.rs"

[[bin]]
name = "d07p1"
path = "src/days/d07p1.rs"

[[bin]]
name = "d07p2"
path = "src/days/d07p2.rs"

[[bin]]
name = "d08p1"
path = "src/days/d08p1.rs"

[[bin]]
name = "d08p2"
path = "src/days/d08p2.rs"

[[bin]]
name = "d09p1"
path = "src/days/d09p1.rs"

[[bin]]
name = "d09p2"
path = "src/days/d09p2.rs"

[[bin]]
name = "d10p1"
path = "src/days/d10p1.rs"

[[bin]]
name = "d10p2"
path = "src/days/d10p2.rs"

[[bin]]
name = "d11p1"
path = "src/days/d11p1.rs"

[[bin]]
name = "d11p2"
path = "src/days/d11p2.rs"

[[bin]]
name = "d12p1"
path = "src/days/d12p1.rs"

[dependencies]
anyhoo = { git = "https://github.com/tranzystorek-io/anyhoo", features = ["reexport"] }
aoc-utils = "0.4"
itertools = "0.10"
scan_fmt = { version = "0.2", default-features = false, features = ["std"] }
